# Generated by Django 3.0.4 on 2020-03-18 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reactapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='tags',
        ),
    ]
